# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-create-pre-release:
    runs-on: ubuntu-latest
    
    permissions:
        actions: write
        attestations: read
        checks: write
        contents: write
        deployments : write
        discussions: read
        issues: read
        packages: write
        pages: write
        pull-requests: write
        repository-projects: write
        security-events: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Unzip REFramework.NET.application.dll
      run: unzip /REFramework/plugins/managed/generated/REFramework.NET.application.zip -d /home/runner/work/MHWs-YURI-Overlay/MHWs-YURI-Overlay/bin/

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Zip the Build
      run: |
        cd /home/runner/work/MHWs-YURI-Overlay/MHWs-YURI-Overlay/bin/ && zip -r YURI_Overlay.zip -- *

    - name: Expose Commit Data
      uses: rlespinasse/git-commit-data-action@v1
        
    - name: Create Build Release
      id: create-build-release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: 0${{ github.run_number }}-${{ env.GIT_COMMIT_SHORT_SHA }}
        name: Build 00${{ github.run_number }} (${{ env.GIT_COMMIT_SHORT_SHA }})
        draft: false
        prerelease: true
        body: '## [Main Repo](https://github.com/GreenComfyTea/MHWs-YURI-Overlay) | [Commit Files](https://github.com/GreenComfyTea/MHWs-YURI-Overlay/tree/${{ env.GIT_COMMIT_SHA }})'
        token: ${{ secrets.NIGHTLY_TOKEN }}
        repo: MHWs-YURI-Overlay-Nightly
        
    - name: Upload Assets to Build Release
      id: upload-assets-to-build-release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      with:
        upload_url: ${{ steps.create-build-release.outputs.upload_url }}
        asset_path: /home/runner/work/MHWs-YURI-Overlay/MHWs-YURI-Overlay/bin/YURI_Overlay.zip
        asset_name: YURI_Overlay_000${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip
        asset_content_type: application/zip
        
    - name: Update Latest Release
      id: update-latest-release
      uses: ncipollo/release-action@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: latest
        name: Nightly 00${{ github.run_number }} (${{ env.GIT_COMMIT_SHORT_SHA }})
        draft: false
        allowUpdates: true
        removeArtifacts: true
        body: '## [Main Repo](https://github.com/GreenComfyTea/MHWs-YURI-Overlay) | [Commit Files](https://github.com/GreenComfyTea/MHWs-YURI-Overlay/tree/${{ env.GIT_COMMIT_SHA }}) | Ignore the date shown for the release. This is the latest build.'
        token: ${{ secrets.NIGHTLY_TOKEN }}
        repo: MHWs-YURI-Overlay-Nightly

    - name: Upload Assets to Latest Release
      id: upload-assets-to-latest-release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_TOKEN }}
      with:
        upload_url: ${{ steps.update-latest-release.outputs.upload_url }}
        asset_path: /home/runner/work/MHWs-YURI-Overlay/MHWs-YURI-Overlay/bin/YURI_Overlay.zip
        asset_name: YURI_Overlay_00${{ github.run_number }}_${{ env.GIT_COMMIT_SHORT_SHA }}.zip
        asset_content_type: application/zip
